# Generated by Django 5.2 on 2025-06-03 14:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('prerequisites', models.TextField(blank=True, default='', null=True)),
                ('date_of_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='Ukryty', max_length=255)),
                ('field_of_study', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.fieldofstudy')),
                ('owner', models.ForeignKey(limit_choices_to={'is_supervisor': True}, on_delete=django.db.models.deletion.CASCADE, related_name='owned_theses', to=settings.AUTH_USER_MODEL)),
                ('producer', models.OneToOneField(default=None, limit_choices_to={'is_student': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thesis_producer', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(to='theses.tag')),
            ],
        ),
    ]
