# Generated by Django 5.2 on 2025-05-15 20:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('theses', '0001_initial'), ('theses', '0002_delete_tag_alter_thesis_tags'), ('theses', '0003_thesis_date_of_creation'), ('theses', '0004_alter_thesis_date_of_creation'), ('theses', '0005_thesis_field_of_study')]

    dependencies = [
        ('accounts', '0004_alter_systemuser_expiration_date_squashed_0009_alter_systemuser_expiration_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('producer_limit', models.PositiveIntegerField(default=1)),
                ('owner', models.ForeignKey(limit_choices_to={'is_supervisor': True}, on_delete=django.db.models.deletion.CASCADE, related_name='owned_theses', to=settings.AUTH_USER_MODEL)),
                ('producers', models.ManyToManyField(limit_choices_to={'is_student': True}, related_name='producing_theses', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(to='accounts.tag')),
                ('date_of_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('field_of_study', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='accounts.fieldofstudy')),
            ],
        ),
    ]
