# Generated by Django 5.2 on 2025-05-05 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('producer_limit', models.PositiveIntegerField(default=1)),
                ('owner', models.ForeignKey(limit_choices_to={'is_supervisor': True}, on_delete=django.db.models.deletion.CASCADE, related_name='owned_theses', to=settings.AUTH_USER_MODEL)),
                ('producers', models.ManyToManyField(limit_choices_to={'is_student': True}, related_name='producing_theses', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(to='theses.tag')),
            ],
        ),
    ]
