# Generated by Django 5.2 on 2025-05-06 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_tag_alter_systemuser_expiration_date_systemuser_tags'),
        ('theses', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AlterField(
            model_name='thesis',
            name='tags',
            field=models.ManyToManyField(to='accounts.tag'),
        ),
    ]
