# Generated by Django 5.2 on 2025-05-08 12:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0002_delete_tag_alter_thesis_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='date_of_creation',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
