# Generated by Django 5.2 on 2025-05-08 14:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0003_thesis_date_of_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='date_of_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
