# Generated by Django 5.2 on 2025-05-09 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_systemuser_expiration_date'),
        ('theses', '0004_alter_thesis_date_of_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='field_of_study',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='accounts.fieldofstudy'),
            preserve_default=False,
        ),
    ]
