# Generated by Django 5.2 on 2025-05-15 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0001_squashed_0005_thesis_field_of_study'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='thesis',
            name='producer_limit',
        ),
        migrations.RemoveField(
            model_name='thesis',
            name='producers',
        ),
        migrations.AddField(
            model_name='thesis',
            name='producer',
            field=models.OneToOneField(limit_choices_to={'is_student': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thesis_producer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='thesis',
            name='status',
            field=models.CharField(default='Ukryty'),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='name',
            field=models.CharField(default=None, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='tags',
            field=models.ManyToManyField(to='theses.tag'),
        ),
    ]
