# Generated by Django 5.2 on 2025-05-15 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('theses', '0007_alter_thesis_producer'), ('theses', '0008_thesis_prerequisites_alter_thesis_description'), ('theses', '0009_alter_thesis_field_of_study')]

    dependencies = [
        ('accounts', '0011_alter_systemuser_expiration_date_squashed_0013_alter_systemuser_expiration_date'),
        ('theses', '0006_tag_remove_thesis_producer_limit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='producer',
            field=models.OneToOneField(default=None, limit_choices_to={'is_student': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thesis_producer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='thesis',
            name='prerequisites',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='field_of_study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.fieldofstudy'),
        ),
    ]
