# Generated by Django 5.2 on 2025-05-15 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0006_tag_remove_thesis_producer_limit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='producer',
            field=models.OneToOneField(default=None, limit_choices_to={'is_student': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thesis_producer', to=settings.AUTH_USER_MODEL),
        ),
    ]
