# Generated by Django 5.2 on 2025-05-15 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0007_alter_thesis_producer'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='prerequisites',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
