# Generated by Django 5.2 on 2025-05-30 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0007_alter_thesis_producer_squashed_0009_alter_thesis_field_of_study'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='field_of_study',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.fieldofstudy'),
        ),
    ]
