# Generated by Django 5.2 on 2025-05-30 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0010_alter_thesis_field_of_study'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='name',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
