# Generated by Django 5.2 on 2025-04-30 21:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldOfStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='systemuser',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2035, 4, 30, 21, 5, 2, 304362, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='systemuser',
            name='field_of_study',
            field=models.ManyToManyField(to='accounts.fieldofstudy'),
        ),
    ]
