# Generated by Django 5.2 on 2025-06-12 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_create_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldofstudy',
            name='description',
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2035, 6, 12, 12, 44, 40, 291286, tzinfo=datetime.timezone.utc)),
        ),
    ]
