# Generated by Django 5.2 on 2025-05-01 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_fieldofstudy_systemuser_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldofstudy',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2035, 5, 1, 14, 37, 23, 279513, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='first_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='last_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
