# Generated by Django 5.2 on 2025-05-06 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_fieldofstudy_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemuser',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2035, 5, 6, 13, 33, 59, 483991, tzinfo=datetime.timezone.utc)),
        ),
    ]
