# Generated by Django 5.2 on 2025-05-05 10:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_fieldofstudy_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemuser',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2035, 5, 5, 10, 23, 28, 726877, tzinfo=datetime.timezone.utc)),
        ),
    ]
