# Generated by Django 5.2 on 2025-05-15 20:02

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('accounts', '0004_alter_systemuser_expiration_date'), ('accounts', '0005_tag_alter_systemuser_expiration_date_systemuser_tags'), ('accounts', '0006_faculty_systemuser_title_and_more'), ('accounts', '0007_fieldofstudy_faculty_and_more'), ('accounts', '0008_alter_systemuser_expiration_date'), ('accounts', '0009_alter_systemuser_expiration_date')]

    dependencies = [
        ('accounts', '0001_initial_squashed_0003_alter_fieldofstudy_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='systemuser',
            name='tags',
            field=models.ManyToManyField(to='accounts.tag'),
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='systemuser',
            name='title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fieldofstudy',
            name='faculty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.faculty'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2035, 5, 9, 7, 45, 25, 210510, tzinfo=datetime.timezone.utc)),
        ),
    ]
