# Generated by Django 5.2 on 2025-05-06 05:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_systemuser_expiration_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2035, 5, 6, 5, 34, 21, 335479, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='systemuser',
            name='tags',
            field=models.ManyToManyField(to='accounts.tag'),
        ),
    ]
