# Generated by Django 5.2 on 2025-05-06 13:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_systemuser_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemuser',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2035, 5, 6, 13, 34, 31, 307218, tzinfo=datetime.timezone.utc)),
        ),
    ]
