# Generated by Django 5.2 on 2025-05-08 12:34

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_faculty_systemuser_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldofstudy',
            name='faculty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.faculty'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2035, 5, 8, 12, 34, 29, 730866, tzinfo=datetime.timezone.utc)),
        ),
    ]
