# Generated by Django 5.2 on 2025-05-08 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_fieldofstudy_faculty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemuser',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2035, 5, 8, 14, 1, 47, 961540, tzinfo=datetime.timezone.utc)),
        ),
    ]
