# Generated by Django 5.2 on 2025-05-09 07:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_systemuser_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemuser',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2035, 5, 9, 7, 45, 25, 210510, tzinfo=datetime.timezone.utc)),
        ),
    ]
