# Generated by Django 5.2 on 2025-05-15 05:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_systemuser_expiration_date_squashed_0009_alter_systemuser_expiration_date'),
        ('theses', '0006_tag_remove_thesis_producer_limit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldofstudy',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='systemuser',
            name='tags',
        ),
        migrations.AddField(
            model_name='systemuser',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2035, 5, 15, 5, 53, 27, 451688, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
