# Generated by Django 5.2 on 2025-05-15 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('accounts', '0011_alter_systemuser_expiration_date'), ('accounts', '0012_alter_systemuser_expiration_date'), ('accounts', '0013_alter_systemuser_expiration_date')]

    dependencies = [
        ('accounts', '0010_remove_fieldofstudy_faculty_remove_systemuser_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemuser',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2035, 5, 15, 13, 14, 49, 868027, tzinfo=datetime.timezone.utc)),
        ),
    ]
