# Generated by Django 5.2 on 2025-05-15 06:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_fieldofstudy_faculty_remove_systemuser_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemuser',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2035, 5, 15, 6, 12, 58, 846888, tzinfo=datetime.timezone.utc)),
        ),
    ]
