# Generated by Django 5.2 on 2025-05-15 07:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_systemuser_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemuser',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2035, 5, 15, 7, 39, 14, 721446, tzinfo=datetime.timezone.utc)),
        ),
    ]
