# Generated by Django 5.1.7 on 2025-05-24 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_systemuser_expiration_date_squashed_0013_alter_systemuser_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='total_spots',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2035, 5, 24, 17, 13, 52, 402320, tzinfo=datetime.timezone.utc)),
        ),
    ]
